import type { ReportPlan, ReportSourceDocument } from "@t3tools/contracts";

const AUTO_REPORT_TITLE_PATTERN = /^OpenReport (?:Draft|Template|Prebuilt Draft)(?: [1-9]\d*)?$/i;
const FINANCIAL_KEYWORDS =
  /\b(?:10-k|10-q|annual report|quarterly report|earnings|financial|revenue|ebitda|profit|loss|cash flow|debt|deleverag|balance sheet|income statement|results?)\b/i;
const EARNINGS_KEYWORDS = /\b(?:earnings|results?|quarterly report|10-q)\b/i;
const BUDGET_KEYWORDS = /\b(?:budget|spend|variance|allocation)\b/i;
const RISK_KEYWORDS = /\b(?:risk|mitigation|exposure)\b/i;
const COMPETITIVE_KEYWORDS = /\b(?:competitor|competitive|market gap|differentiator)\b/i;
const EXECUTIVE_KEYWORDS = /\b(?:executive brief|leadership|board|decision memo)\b/i;
const SECTION_SUFFIX_PATTERN = / Structure$/i;
const ENTITY_STOP_WORDS = new Set([
  "annual",
  "earning",
  "earnings",
  "financial",
  "presentation",
  "quarterly",
  "report",
  "reports",
  "result",
  "results",
  "statement",
  "statements",
]);

function normalizeCandidateReportTitle(title: string | null | undefined): string | null {
  const normalized = title?.replace(/\s+/g, " ").trim() ?? "";
  return normalized.length > 0 ? normalized : null;
}

export function isAutoGeneratedReportTitle(title: string): boolean {
  const normalized = normalizeCandidateReportTitle(title);
  if (!normalized) {
    return false;
  }
  return AUTO_REPORT_TITLE_PATTERN.test(normalized.replace(SECTION_SUFFIX_PATTERN, ""));
}

function normalizeTitlePart(value: string): string {
  return value.replace(/[_-]+/g, " ").replace(/\s+/g, " ").trim();
}

function normalizeYear(value: string): string {
  if (value.length === 2) {
    return `20${value}`;
  }
  return value;
}

function inferQuarterFromMonth(month: string): string | null {
  const normalized = month.toLowerCase();
  if (["jan", "january", "feb", "february", "mar", "march"].includes(normalized)) {
    return "Q1";
  }
  if (["apr", "april", "may", "jun", "june"].includes(normalized)) {
    return "Q2";
  }
  if (["jul", "july", "aug", "august", "sep", "sept", "september"].includes(normalized)) {
    return "Q3";
  }
  if (["oct", "october", "nov", "november", "dec", "december"].includes(normalized)) {
    return "Q4";
  }
  return null;
}

function titleContainsPeriod(title: string, periodLabel: string): boolean {
  const normalizedTitle = title.toLowerCase();
  const normalizedPeriod = periodLabel.toLowerCase();
  if (normalizedTitle.includes(normalizedPeriod)) {
    return true;
  }

  const quarterMatch = /^Q([1-4]) (20\d{2})$/.exec(periodLabel);
  return quarterMatch
    ? normalizedTitle.includes(`${quarterMatch[2]} q${quarterMatch[1]}`) ||
        normalizedTitle.includes(`q${quarterMatch[1]} fy${quarterMatch[2]}`)
    : false;
}

function collectTitleContext(input: {
  readonly brief: string;
  readonly fileRefs: ReadonlyArray<string>;
  readonly documents?: ReadonlyArray<ReportSourceDocument>;
}): string {
  const documentContext =
    input.documents
      ?.map((document) => `${document.name}\n${document.textContent.slice(0, 4000)}`)
      .join("\n") ?? "";
  return [input.brief, ...input.fileRefs, documentContext].join("\n");
}

export function inferReportPeriodLabel(input: {
  readonly brief: string;
  readonly fileRefs: ReadonlyArray<string>;
  readonly documents?: ReadonlyArray<ReportSourceDocument>;
}): string | null {
  const context = collectTitleContext(input);
  const patterns: ReadonlyArray<RegExp> = [
    /\bQ([1-4])\s*(?:[-_/ ]|)?(?:FY\s*)?(20\d{2}|\d{2})\b/i,
    /\b(?:FY\s*)?(20\d{2}|\d{2})\s*(?:[-_/ ]|)?Q([1-4])\b/i,
  ];

  for (const pattern of patterns) {
    const match = pattern.exec(context);
    if (!match) {
      continue;
    }
    const first = match[1]!;
    const second = match[2]!;
    if (/^[1-4]$/.test(first)) {
      return `Q${first} ${normalizeYear(second)}`;
    }
    return `Q${second} ${normalizeYear(first)}`;
  }

  const quarterEndedMatch =
    /\b(?:quarter|three months|period)\s+ended\s+([A-Za-z]+)\s+\d{1,2},?\s+(20\d{2})\b/i.exec(
      context,
    );
  if (quarterEndedMatch) {
    const quarter = inferQuarterFromMonth(quarterEndedMatch[1]!);
    if (quarter) {
      return `${quarter} ${quarterEndedMatch[2]}`;
    }
  }

  const looseQuarterMatch = /\bQ([1-4])\b/i.exec(context);
  const looseFiscalYearMatch = /\b(?:FY|fiscal year)\s*(20\d{2}|\d{2})\b/i.exec(context);
  if (looseQuarterMatch && looseFiscalYearMatch) {
    return `Q${looseQuarterMatch[1]} ${normalizeYear(looseFiscalYearMatch[1]!)}`;
  }

  const fiscalYearMatch = /\b(?:FY|fiscal year)\s*(20\d{2}|\d{2})\b/i.exec(context);
  if (fiscalYearMatch) {
    return `FY${normalizeYear(fiscalYearMatch[1]!)}`;
  }

  const annualYearMatch =
    /\b(?:annual report|year ended|fiscal year ended)\b[\s\S]{0,80}\b(20\d{2})\b/i.exec(context) ??
    /\b(20\d{2})\b[\s\S]{0,80}\bannual report\b/i.exec(context);
  return annualYearMatch ? `FY${annualYearMatch[1]}` : null;
}

function inferEntityFromFileRefs(fileRefs: ReadonlyArray<string>): string | null {
  for (const fileRef of fileRefs) {
    const name = normalizeTitlePart(
      fileRef
        .split(/[\\/]/)
        .at(-1)
        ?.replace(/\.[a-z0-9]+$/i, "") ?? "",
    );
    const tokens = name.split(" ").filter(Boolean);
    const entityTokens: string[] = [];
    let started = false;

    for (const token of tokens) {
      const normalized = token.toLowerCase();
      if (
        /^q[1-4]$/i.test(token) ||
        /^fy?\d{2,4}$/i.test(token) ||
        /^20\d{2}$/.test(token) ||
        /^\d{4}$/.test(token)
      ) {
        started = true;
        continue;
      }
      if (ENTITY_STOP_WORDS.has(normalized)) {
        break;
      }
      if (started || entityTokens.length > 0) {
        entityTokens.push(token);
      }
    }

    const entity = entityTokens.join(" ").trim();
    if (entity.length > 0) {
      return entity;
    }
  }
  return null;
}

function inferReportSubject(input: {
  readonly brief: string;
  readonly fileRefs: ReadonlyArray<string>;
  readonly documents?: ReadonlyArray<ReportSourceDocument>;
}): string {
  const context = collectTitleContext(input);
  const entity = inferEntityFromFileRefs(input.fileRefs);
  const descriptor = EARNINGS_KEYWORDS.test(context)
    ? "Earnings Report"
    : FINANCIAL_KEYWORDS.test(context)
      ? "Financial Performance Report"
      : BUDGET_KEYWORDS.test(context)
        ? "Budget Variance Report"
        : RISK_KEYWORDS.test(context)
          ? "Risk Assessment Report"
          : COMPETITIVE_KEYWORDS.test(context)
            ? "Competitive Analysis Report"
            : EXECUTIVE_KEYWORDS.test(context)
              ? "Executive Brief"
              : "Report Summary";

  return entity ? `${entity} ${descriptor}` : descriptor;
}

export function buildContextualReportTitle(input: {
  readonly fallbackTitle: string;
  readonly brief: string;
  readonly fileRefs: ReadonlyArray<string>;
  readonly documents?: ReadonlyArray<ReportSourceDocument>;
}): string {
  const normalizedFallback =
    normalizeCandidateReportTitle(input.fallbackTitle)?.replace(SECTION_SUFFIX_PATTERN, "") ??
    "Report";
  const periodLabel = inferReportPeriodLabel(input);
  const baseTitle = isAutoGeneratedReportTitle(normalizedFallback)
    ? inferReportSubject(input)
    : normalizedFallback;

  if (!periodLabel || titleContainsPeriod(baseTitle, periodLabel)) {
    return baseTitle;
  }

  return `${periodLabel} ${baseTitle}`;
}

export function applyAutomaticPlanningTitle(input: {
  readonly currentTitle: string;
  readonly plan: ReportPlan;
}): { readonly title: string; readonly plan: ReportPlan } {
  if (!isAutoGeneratedReportTitle(input.currentTitle)) {
    return { title: input.currentTitle, plan: input.plan };
  }

  const candidate = normalizeCandidateReportTitle(input.plan.planning.proposedOutline?.title);
  if (!candidate || isAutoGeneratedReportTitle(candidate) || candidate === input.currentTitle) {
    return { title: input.currentTitle, plan: input.plan };
  }

  return {
    title: candidate,
    plan: {
      ...input.plan,
      metadata: {
        ...input.plan.metadata,
        title: candidate,
      },
    },
  };
}
