import { describe, expect, it } from "vitest";

import type { ReportPlan } from "@t3tools/contracts";

import {
  applyAutomaticPlanningTitle,
  buildContextualReportTitle,
  inferReportPeriodLabel,
  isAutoGeneratedReportTitle,
} from "./title.ts";

function makePlan(overrides?: Partial<ReportPlan>): ReportPlan {
  return {
    version: "1.0",
    status: "draft",
    metadata: {
      title: "OpenReport Draft 5",
      reportType: "user_guided",
      audience: "general",
      tone: "clear, analytical",
      brief: "Summarize the uploaded documents.",
      targetLength: {
        minWords: 1200,
        maxWords: 1800,
      },
      outputFormats: ["markdown"],
      language: "en",
      citationStyle: "inline",
    },
    globalSourceConfig: {
      webSearch: {
        enabled: true,
        preferredDomains: [],
        recencyFilter: null,
        queriesHint: [],
      },
      userDocuments: {
        enabled: true,
        fileRefs: [],
        documents: [],
      },
      knowledgeBase: {
        enabled: false,
        collectionId: null,
      },
    },
    documentProfiles: [],
    sectionTree: [],
    crossCuttingInstructions: {
      dataPresentation: "Use bullets when helpful.",
      consistencyRules: [],
      excludedTopics: [],
    },
    orchestration: {
      modelSelection: null,
      agentSwarm: {
        orchestratorModel: null,
        sectionAgentModel: null,
        enabledTools: ["search_documents"],
        maxToolCallsPerSection: 8,
        maxSectionRetries: 3,
      },
    },
    planning: {
      status: "awaiting-approval",
      pendingQuestions: [],
      conversation: [],
      proposedOutline: {
        title: "Group Financial Performance & Deleveraging",
        summary: "A decision-ready structure for the current report brief.",
        sections: [],
      },
      lastOrchestratedAt: "2026-04-20T10:00:00.000Z",
    },
    ...overrides,
  };
}

describe("report title automation", () => {
  it("detects autogenerated OpenReport placeholder titles", () => {
    expect(isAutoGeneratedReportTitle("OpenReport Draft")).toBe(true);
    expect(isAutoGeneratedReportTitle("OpenReport Draft 5")).toBe(true);
    expect(isAutoGeneratedReportTitle("OpenReport Draft 5 Structure")).toBe(true);
    expect(isAutoGeneratedReportTitle("Group Financial Performance")).toBe(false);
  });

  it("promotes generated planning outline titles for placeholder report names", () => {
    const result = applyAutomaticPlanningTitle({
      currentTitle: "OpenReport Draft 5",
      plan: makePlan(),
    });

    expect(result.title).toBe("Group Financial Performance & Deleveraging");
    expect(result.plan.metadata.title).toBe("Group Financial Performance & Deleveraging");
  });

  it("does not overwrite manually renamed reports", () => {
    const plan = makePlan({
      metadata: {
        ...makePlan().metadata,
        title: "Custom Board Report",
      },
    });

    const result = applyAutomaticPlanningTitle({
      currentTitle: "Custom Board Report",
      plan,
    });

    expect(result.title).toBe("Custom Board Report");
    expect(result.plan.metadata.title).toBe("Custom Board Report");
  });

  it("ignores placeholder outline titles from deterministic planning fallbacks", () => {
    const plan = makePlan({
      planning: {
        ...makePlan().planning,
        proposedOutline: {
          title: "OpenReport Draft 5 Structure",
          summary: "A generic structure.",
          sections: [],
        },
      },
    });

    const result = applyAutomaticPlanningTitle({
      currentTitle: "OpenReport Draft 5",
      plan,
    });

    expect(result.title).toBe("OpenReport Draft 5");
    expect(result.plan.metadata.title).toBe("OpenReport Draft 5");
  });

  it("infers quarter and year from financial filenames", () => {
    const input = {
      brief: "Create a concise financial performance report for leadership.",
      fileRefs: ["Q4-Tata-Motors-Ltd-Earnings-Release-FY2026.pdf"],
      documents: [],
    };

    expect(inferReportPeriodLabel(input)).toBe("Q4 2026");
    expect(
      buildContextualReportTitle({
        fallbackTitle: "OpenReport Draft 5",
        ...input,
      }),
    ).toBe("Q4 2026 Tata Motors Ltd Earnings Report");
  });

  it("infers quarter from period-ended source text", () => {
    expect(
      inferReportPeriodLabel({
        brief: "Summarize the attached financial results.",
        fileRefs: ["results.pdf"],
        documents: [
          {
            name: "results.pdf",
            mimeType: "application/pdf",
            textContent: "Unaudited results for the quarter ended March 31, 2026.",
          },
        ],
      }),
    ).toBe("Q1 2026");
  });
});
